<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-IntegrationWorker.Service-d5a9b71c-2531-4d16-9b81-534c2ffd5717</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Dockerfile" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
  </ItemGroup>
</Project>
